name: CI_testing

on:
  push:
    branches:
    - server_restructuring

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '10.x'
    - run: npm install
    - run: npm run build --prod
    # - run: npm install -g @angular/cli
    # - run: ng build --prod
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting:testing
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  
  backend-deploy:
    
    defaults:
      run:
        working-directory: ./backend
    
    runs-on: ubuntu-latest
    
    steps:
    - id: deploy
      uses: google-github-actions/deploy-appengine@main
      with:
        credentials: ${{ secrets.GCP_SA_KEY  }}
        project_id: ${{ secrets.GCP_PROJECT }}
        working_directory: ./backend
        deliverables: app.yaml
